#1) Loading dataset

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Renewable_Energy_Dataset.csv to Renewable_Energy_Dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv("Renewable_Energy_Dataset.csv")

df.head()

,Country,Solar_Energy_MW,Wind_Energy_MW,Hydropower_MW,Carbon_Emissions_MT,Renewable_Percentage,Population_Millions
0,India,85000.0,45000.0,51000,2500,42.0,1430
1,USA,120000.0,130000.0,80000,5000,35.0,340
2,China,300000.0,280000.0,350000,10000,30.0,1410
3,Germany,70000.0,65000.0,25000,800,55.0,84
4,Brazil,50000.0,30000.0,110000,600,60.0,216

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               15 non-null     object
 1   Solar_Energy_MW       14 non-null     float64
 2   Wind_Energy_MW        14 non-null     float64
 3   Hydropower_MW         15 non-null     int64
 4   Carbon_Emissions_MT   15 non-null     int64
 5   Renewable_Percentage  14 non-null     float64
 6   Population_Millions   15 non-null     int64
dtypes: float64(3), int64(3), object(1)
memory usage: 972.0+ bytes

## Dataset Overview

- The dataset contains information about renewable energy production and sustainability indicators for different countries.
- It includes solar energy, wind energy, hydropower generation, carbon emissions, renewable energy percentage, and population.
- The dataset will be analyzed to understand relationships between renewable energy production and sustainability metrics.

#2) Check for null values

In [5]:
df.isnull().sum()

Country                 0
Solar_Energy_MW         1
Wind_Energy_MW          1
Hydropower_MW           0
Carbon_Emissions_MT     0
Renewable_Percentage    1
Population_Millions     0
dtype: int64

## Null Value Analysis

- The dataset contains missing values in:
  - Solar_Energy_MW
  - Wind_Energy_MW
  - Renewable_Percentage

- Since these are numerical columns and the missing values are few,
  replacing them with the mean value of their respective columns is a
  reasonable approach.

#3) Handle the null values

In [6]:
df["Solar_Energy_MW"] = df["Solar_Energy_MW"].fillna(df["Solar_Energy_MW"].mean())

df["Wind_Energy_MW"] = df["Wind_Energy_MW"].fillna(df["Wind_Energy_MW"].mean())

df["Renewable_Percentage"] = df["Renewable_Percentage"].fillna(df["Renewable_Percentage"].mean())

In [7]:
df.isnull().sum()

Country                 0
Solar_Energy_MW         0
Wind_Energy_MW          0
Hydropower_MW           0
Carbon_Emissions_MT     0
Renewable_Percentage    0
Population_Millions     0
dtype: int64

## Null Value Handling

- Missing values in numerical columns were replaced using the mean value
  of the respective column.
- Mean imputation helps preserve the dataset size and avoids introducing
  extreme values into the analysis.

# 4) Relationship Analysis Between Features

1. Solar_Energy_MW, Wind_Energy_MW, and Hydropower_MW are renewable energy sources and contribute positively to sustainability.

2. Countries with higher Renewable_Percentage generally rely more on clean energy sources.

3. Carbon_Emissions_MT is expected to have an inverse relationship with Renewable_Percentage.
   Countries using more renewable energy tend to have lower carbon emissions.

4. Population_Millions may influence total energy production and carbon emissions because larger populations require more energy.

5. Countries with higher renewable energy production often invest more in sustainable technologies and infrastructure.

6. Hydropower_MW contributes significantly to the renewable energy mix in countries with abundant water resources.

7. Renewable energy production and sustainability indicators help assess a country's environmental performance.

###Dataset dimensions

In [8]:
print("Dataset Shape:", df.shape)

Dataset Shape: (15, 7)

###Column names

In [9]:
print(df.columns)

Index(['Country', 'Solar_Energy_MW', 'Wind_Energy_MW', 'Hydropower_MW',
       'Carbon_Emissions_MT', 'Renewable_Percentage', 'Population_Millions'],
      dtype='object')

###Statistical summary

In [10]:
df.describe()

,Solar_Energy_MW,Wind_Energy_MW,Hydropower_MW,Carbon_Emissions_MT,Renewable_Percentage,Population_Millions
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,67142.857143,59285.714286,66600.000000,1608.000000,53.142857,266.066667
std,70205.674519,68069.742147,84722.909703,2635.125912,16.199017,476.390666
min,12000.000000,8000.000000,5000.000000,100.000000,28.000000,5.000000
25%,37500.000000,26500.000000,19000.000000,425.000000,45.000000,44.000000
50%,50000.000000,35000.000000,51000.000000,600.000000,53.142857,68.000000
75%,68571.428571,62142.857143,75000.000000,1050.000000,59.000000,170.500000
max,300000.000000,280000.000000,350000.000000,10000.000000,85.000000,1430.000000

###Countries with highest renewable percentage

In [11]:
df.sort_values(by="Renewable_Percentage", ascending=False)

,Country,Solar_Energy_MW,Wind_Energy_MW,Hydropower_MW,Carbon_Emissions_MT,Renewable_Percentage,Population_Millions
12,Norway,15000.000000,12000.000000,70000,120,85.000000,5
13,Sweden,18000.000000,22000.000000,65000,100,82.000000,10
10,Spain,55000.000000,50000.000000,20000,350,62.000000,48
4,Brazil,50000.000000,30000.000000,110000,600,60.000000,216
5,Canada,45000.000000,59285.714286,90000,700,58.000000,40
9,UK,45000.000000,70000.000000,10000,400,57.000000,68
3,Germany,70000.000000,65000.000000,25000,800,55.000000,84
8,Japan,50000.000000,25000.000000,30000,1200,53.142857,125
7,France,40000.000000,35000.000000,60000,450,52.000000,68
11,Italy,67142.857143,28000.000000,18000,500,50.000000,59
6,Australia,35000.000000,30000.000000,15000,500,48.000000,27
0,India,85000.000000,45000.000000,51000,2500,42.000000,1430
1,USA,120000.000000,130000.000000,80000,5000,35.000000,340
2,China,300000.000000,280000.000000,350000,10000,30.000000,1410
14,South Africa,12000.000000,8000.000000,5000,900,28.000000,61

###Countries with highest carbon emissions

In [12]:
df.sort_values(by="Carbon_Emissions_MT", ascending=False)

,Country,Solar_Energy_MW,Wind_Energy_MW,Hydropower_MW,Carbon_Emissions_MT,Renewable_Percentage,Population_Millions
2,China,300000.000000,280000.000000,350000,10000,30.000000,1410
1,USA,120000.000000,130000.000000,80000,5000,35.000000,340
0,India,85000.000000,45000.000000,51000,2500,42.000000,1430
8,Japan,50000.000000,25000.000000,30000,1200,53.142857,125
14,South Africa,12000.000000,8000.000000,5000,900,28.000000,61
3,Germany,70000.000000,65000.000000,25000,800,55.000000,84
5,Canada,45000.000000,59285.714286,90000,700,58.000000,40
4,Brazil,50000.000000,30000.000000,110000,600,60.000000,216
6,Australia,35000.000000,30000.000000,15000,500,48.000000,27
11,Italy,67142.857143,28000.000000,18000,500,50.000000,59
7,France,40000.000000,35000.000000,60000,450,52.000000,68
9,UK,45000.000000,70000.000000,10000,400,57.000000,68
10,Spain,55000.000000,50000.000000,20000,350,62.000000,48
12,Norway,15000.000000,12000.000000,70000,120,85.000000,5
13,Sweden,18000.000000,22000.000000,65000,100,82.000000,10

###Average values

In [13]:
df.mean(numeric_only=True)

Solar_Energy_MW         67142.857143
Wind_Energy_MW          59285.714286
Hydropower_MW           66600.000000
Carbon_Emissions_MT      1608.000000
Renewable_Percentage       53.142857
Population_Millions       266.066667
dtype: float64

## Observations

- Norway and Sweden have very high renewable energy percentages.
- China and the USA have the highest carbon emissions due to large industrial activities.
- Countries with higher renewable energy adoption generally have lower carbon emissions.
- Population size affects energy demand and overall emissions.
- Renewable energy sources play a major role in sustainable development.

#5) Final Summary



In this task, a sustainability dataset related to renewable energy was imported using Pandas.

The dataset was explored and analyzed to understand relationships between renewable energy production, carbon emissions, and population.

Missing values were identified and handled using mean imputation.

Various Pandas functions were used to inspect, analyze, and summarize the dataset.

This analysis demonstrates how data science can be used to support sustainability and green energy initiatives.