In [1]:
from google.colab import files

uploaded = files.upload()

Saving Untitled spreadsheet - Sheet1.csv to Untitled spreadsheet - Sheet1.csv

In [2]:
import pandas as pd

df = pd.read_csv("Untitled spreadsheet - Sheet1.csv")

print(df)

     Name  Age       City  Marks
0  Shriya   21  Ahmedabad     85
1   Rahul   22      Surat     78
2   Priya   20   Vadodara     92
3    Amit   23     Rajkot     88
4    Neha   21  Ahmedabad     95

##Method 1: head()

In [3]:
df.head()

     Name  Age       City  Marks
0  Shriya   21  Ahmedabad     85
1   Rahul   22      Surat     78
2   Priya   20   Vadodara     92
3    Amit   23     Rajkot     88
4    Neha   21  Ahmedabad     95

##Method 2: tail()

In [5]:
df.tail()

     Name  Age       City  Marks
0  Shriya   21  Ahmedabad     85
1   Rahul   22      Surat     78
2   Priya   20   Vadodara     92
3    Amit   23     Rajkot     88
4    Neha   21  Ahmedabad     95

##Method 3: shape

In [6]:
df.shape

(5, 4)

##Method 4: columns

In [7]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

##Method 5: info()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Marks   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

##Method 6: describe()

In [9]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   21.400000  87.600000
std     1.140175   6.580274
min    20.000000  78.000000
25%    21.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  92.000000
max    23.000000  95.000000

##Method 7: isnull()

In [10]:
df.isnull()

    Name    Age   City  Marks
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

##Method 8: isnull().sum()

In [11]:
df.isnull().sum()

Name     0
Age      0
City     0
Marks    0
dtype: int64

##Method 9: sort_values()

In [12]:
df.sort_values(by='Marks')

     Name  Age       City  Marks
1   Rahul   22      Surat     78
0  Shriya   21  Ahmedabad     85
3    Amit   23     Rajkot     88
2   Priya   20   Vadodara     92
4    Neha   21  Ahmedabad     95

##Method 10: value_counts()

In [13]:
df['City'].value_counts()

City
Ahmedabad    2
Surat        1
Vadodara     1
Rajkot       1
Name: count, dtype: int64